# -*- coding: utf-8 -*-
import re
from django.db import models
from django.contrib.auth.models import User
from django.core import validators
from django.contrib.auth.hashers import make_password

CIUDAD = (
	("", "Seleccione una ciudad"),
	("Abejorral", "Abejorral"),
	("Abrego", "Abrego"),
	("Abriaqui", "Abriaqui"),
	("Acacias", "Acacias"),
	("Acandi", "Acandi"),
	("Acevedo", "Acevedo"),
	("Achi", "Achi"),
	("Agrado", "Agrado"),
	("Agua de Dios", "Agua de Dios"),
	("Aguachica", "Aguachica"),
	("Aguada", "Aguada"),
	("Aguadas", "Aguadas"),
	("Aguazul", "Aguazul"),
	("Agustin Codazzi", "Agustin Codazzi"),
	("Aipe", "Aipe"),
	("Alban", "Alban"),
	("Alban (San Jose)", "Alban (San Jose)"),
	("Albania", "Albania"),
	("Alcala", "Alcala"),
	("Aldana", "Aldana"),
	("Alejandria", "Alejandria"),
	("Algeciras", "Algeciras"),
	("Almaguer", "Almaguer"),
	("Almeida", "Almeida"),
	("Alpujarra", "Alpujarra"),
	("Altamira", "Altamira"),
	("Alto Baudo (Pie de Pato)", "Alto Baudo (Pie de Pato)"),
	("Altos del Rosario", "Altos del Rosario"),
	("Alvarado", "Alvarado"),
	("Amaga", "Amaga"),
	("Amalfi", "Amalfi"),
	("Ambalema", "Ambalema"),
	("Anapoima", "Anapoima"),
	("Ancuya", "Ancuya"),
	("Andalucia", "Andalucia"),
	("Andes", "Andes"),
	("Angelopolis", "Angelopolis"),
	("Angostura", "Angostura"),
	("Anolaima", "Anolaima"),
	("Anori", "Anori"),
	("Anserma", "Anserma"),
	("Ansermanuevo", "Ansermanuevo"),
	("Antioquia", "Antioquia"),
	("Anza", "Anza"),
	("Anzoategui", "Anzoategui"),
	("Apartado", "Apartado"),
	("Apia", "Apia"),
	("Aquitania", "Aquitania"),
	("Aracataca", "Aracataca"),
	("Aranzazu", "Aranzazu"),
	("Aratoca", "Aratoca"),
	("Arauca", "Arauca"),
	("Arauquita", "Arauquita"),
	("Arbelaez", "Arbelaez"),
	("Arboleda (Berruecos)", "Arboleda (Berruecos)"),
	("Arboledas", "Arboledas"),
	("Arboletes", "Arboletes"),
	("Arcabuco", "Arcabuco"),
	("Arenal", "Arenal"),
	("Argelia", "Argelia"),
	("Ariguani (El Dificil)", "Ariguani (El Dificil)"),
	("Arjona", "Arjona"),
	("Armenia", "Armenia"),
	("Armero (Guayabal)", "Armero (Guayabal)"),
	("Arroyohondo", "Arroyohondo"),
	("Astrea", "Astrea"),
	("Ataco", "Ataco"),
	("Atrato (Yuto)", "Atrato (Yuto)"),
	("Ayapel", "Ayapel"),
	("Bagado", "Bagado"),
	("Bahia Solano (Mútis)", "Bahia Solano (Mútis)"),
	("Bajo Baudo (Pizarro)", "Bajo Baudo (Pizarro)"),
	("Balboa", "Balboa"),
	("Baranoa", "Baranoa"),
	("Baraya", "Baraya"),
	("Barbacoas", "Barbacoas"),
	("Barbosa", "Barbosa"),
	("Barichara", "Barichara"),
	("Barranca de Upia", "Barranca de Upia"),
	("Barrancabermeja", "Barrancabermeja"),
	("Barrancas", "Barrancas"),
	("Barranco de Loba", "Barranco de Loba"),
	("Barranquilla", "Barranquilla"),
	("Becerril", "Becerril"),
	("Belalcazar", "Belalcazar"),
	("Belen", "Belen"),
	("Belen de los Andaquies", "Belen de los Andaquies"),
	("Belen de Umbria", "Belen de Umbria"),
	("Bello", "Bello"),
	("Belmira", "Belmira"),
	("Beltran", "Beltran"),
	("Berbeo", "Berbeo"),
	("Betania", "Betania"),
	("Beteitiva", "Beteitiva"),
	("Betulia", "Betulia"),
	("Bituima", "Bituima"),
	("Boavita", "Boavita"),
	("Bochalema", "Bochalema"),
	("Bojaca", "Bojaca"),
	("Bojaya (Bellavista)", "Bojaya (Bellavista)"),
	("Bolivar", "Bolivar"),
	("Bosconia", "Bosconia"),
	("Boyaca", "Boyaca"),
	("Briseño", "Briseño"),
	("Bucaramanga", "Bucaramanga"),
	("Bucarasica", "Bucarasica"),
	("Buenaventura", "Buenaventura"),
	("Buenavista", "Buenavista"),
	("Buenos Aires", "Buenos Aires"),
	("Buesaco", "Buesaco"),
	("Buga", "Buga"),
	("Bugalagrande", "Bugalagrande"),
	("Buritica", "Buritica"),
	("Busbanza", "Busbanza"),
	("Cabrera", "Cabrera"),
	("Cabuyaro", "Cabuyaro"),
	("Caceres", "Caceres"),
	("Cachipay", "Cachipay"),
	("Cachira", "Cachira"),
	("Cacota", "Cacota"),
	("Caicedo", "Caicedo"),
	("Caicedonia", "Caicedonia"),
	("Caimito", "Caimito"),
	("Cajamarca", "Cajamarca"),
	("Cajibio", "Cajibio"),
	("Cajica", "Cajica"),
	("Calamar", "Calamar"),
	("Calarca", "Calarca"),
	("Caldas", "Caldas"),
	("Caldono", "Caldono"),
	("Cali", "Cali"),
	("California", "California"),
	("Calima (Darien)", "Calima (Darien)"),
	("Caloto", "Caloto"),
	("Campamento", "Campamento"),
	("Campo de la Cruz", "Campo de la Cruz"),
	("Campoalegre", "Campoalegre"),
	("Campohermoso", "Campohermoso"),
	("Canalete", "Canalete"),
	("Candelaria", "Candelaria"),
	("Cantagallo", "Cantagallo"),
	("Canton de San Pablo", "Canton de San Pablo"),
	("Cañasgordas", "Cañasgordas"),
	("Caparrapi", "Caparrapi"),
	("Capitanejo", "Capitanejo"),
	("Caqueza", "Caqueza"),
	("Caracoli", "Caracoli"),
	("Caramanta", "Caramanta"),
	("Carcasi", "Carcasi"),
	("Carepa", "Carepa"),
	("Carmen de Apicala", "Carmen de Apicala"),
	("Carmen de Carupa", "Carmen de Carupa"),
	("Carmen de Viboral", "Carmen de Viboral"),
	("Carolina", "Carolina"),
	("Cartagena", "Cartagena"),
	("Cartagena del Chaira", "Cartagena del Chaira"),
	("Cartago", "Cartago"),
	("Carurú", "Carurú"),
	("Casabianca", "Casabianca"),
	("Castilla la Nueva", "Castilla la Nueva"),
	("Caucasia", "Caucasia"),
	("Cepita", "Cepita"),
	("Cerete", "Cerete"),
	("Cerinza", "Cerinza"),
	("Cerrito", "Cerrito"),
	("Cerro San Antonio", "Cerro San Antonio"),
	("Chachagüi", "Chachagüi"),
	("Chaguani", "Chaguani"),
	("Chalan", "Chalan"),
	("Chameza", "Chameza"),
	("Chaparral", "Chaparral"),
	("Charala", "Charala"),
	("Charta", "Charta"),
	("Chia", "Chia"),
	("Chigorodo", "Chigorodo"),
	("Chima", "Chima"),
	("Chimichagua", "Chimichagua"),
	("Chinacota", "Chinacota"),
	("Chinavita", "Chinavita"),
	("Chinchina", "Chinchina"),
	("Chinú", "Chinú"),
	("Chipaque", "Chipaque"),
	("Chipata", "Chipata"),
	("Chiquinquira", "Chiquinquira"),
	("Chiquiza", "Chiquiza"),
	("Chiriguana", "Chiriguana"),
	("Chiscas", "Chiscas"),
	("Chita", "Chita"),
	("Chitaga", "Chitaga"),
	("Chitaranque", "Chitaranque"),
	("Chivata", "Chivata"),
	("Chivolo", "Chivolo"),
	("Chivor", "Chivor"),
	("Choachi", "Choachi"),
	("Choconta", "Choconta"),
	("Cicuto", "Cicuto"),
	("Cienaga", "Cienaga"),
	("Cienaga de Oro", "Cienaga de Oro"),
	("Cimitarra", "Cimitarra"),
	("Circasia", "Circasia"),
	("Cisneros", "Cisneros"),
	("Clemencia", "Clemencia"),
	("Cocorna", "Cocorna"),
	("Coello", "Coello"),
	("Cogua", "Cogua"),
	("Colombia", "Colombia"),
	("Colon", "Colon"),
	("Colon (Genova)", "Colon (Genova)"),
	("Coloso (Ricaurte)", "Coloso (Ricaurte)"),
	("Combita", "Combita"),
	("Concepcion", "Concepcion"),
	("Concordia", "Concordia"),
	("Condoto", "Condoto"),
	("Confines", "Confines"),
	("Consaca", "Consaca"),
	("Contadero", "Contadero"),
	("Contratacion", "Contratacion"),
	("Convencion", "Convencion"),
	("Copacabana", "Copacabana"),
	("Coper", "Coper"),
	("Cordoba", "Cordoba"),
	("Corinto", "Corinto"),
	("Coromoro", "Coromoro"),
	("Corozal", "Corozal"),
	("Corrales", "Corrales"),
	("Cota", "Cota"),
	("Cotorra", "Cotorra"),
	("Covarachia", "Covarachia"),
	("Coyaima", "Coyaima"),
	("Cravo Norte", "Cravo Norte"),
	("Cuaspud (Carlosama)", "Cuaspud (Carlosama)"),
	("Cubar", "Cubar"),
	("Cubarral", "Cubarral"),
	("Cucaita", "Cucaita"),
	("Cucunuba", "Cucunuba"),
	("Cúcuta", "Cúcuta"),
	("Cucutilla", "Cucutilla"),
	("Cuitiva", "Cuitiva"),
	("Cumaral", "Cumaral"),
	("Cumaribo", "Cumaribo"),
	("Cumbal", "Cumbal"),
	("Cumbitara", "Cumbitara"),
	("Cunday", "Cunday"),
	("Curillo", "Curillo"),
	("Curiti", "Curiti"),
	("Curumani", "Curumani"),
	("Dabeiba", "Dabeiba"),
	("Dagua", "Dagua"),
	("Dibulla", "Dibulla"),
	("Distraccion", "Distraccion"),
	("Dolores", "Dolores"),
	("Don Matias", "Don Matias"),
	("Dos Quebradas", "Dos Quebradas"),
	("Duitama", "Duitama"),
	("Durania", "Durania"),
	("Ebejico", "Ebejico"),
	("El Águila", "El Águila"),
	("El Bagre", "El Bagre"),
	("El Banco", "El Banco"),
	("El Cairo", "El Cairo"),
	("El Calvario", "El Calvario"),
	("El Carmen", "El Carmen"),
	("El Carmen de Bolivar", "El Carmen de Bolivar"),
	("El Castillo", "El Castillo"),
	("El Cerrito", "El Cerrito"),
	("El Charco", "El Charco"),
	("El Cocuy", "El Cocuy"),
	("El Colegio", "El Colegio"),
	("El Copey", "El Copey"),
	("El Doncello", "El Doncello"),
	("El Dorado", "El Dorado"),
	("El Dovio", "El Dovio"),
	("El Espino", "El Espino"),
	("El Guacamayo", "El Guacamayo"),
	("El Guamo", "El Guamo"),
	("El Litoral de San Juan", "El Litoral de San Juan"),
	("El Molino", "El Molino"),
	("El Paso", "El Paso"),
	("El Paujil", "El Paujil"),
	("El Peñon", "El Peñon"),
	("El Piñon", "El Piñon"),
	("El Playon", "El Playon"),
	("El Reten", "El Reten"),
	("El Retorno", "El Retorno"),
	("El Rosal", "El Rosal"),
	("El Rosario", "El Rosario"),
	("El Tablon", "El Tablon"),
	("El Tambo", "El Tambo"),
	("El Tarra", "El Tarra"),
	("El Zulia", "El Zulia"),
	("Elias", "Elias"),
	("Encino", "Encino"),
	("Enciso", "Enciso"),
	("Entrerrios", "Entrerrios"),
	("Envigado", "Envigado"),
	("Espinal", "Espinal"),
	("Facatativa", "Facatativa"),
	("Falan", "Falan"),
	("Filadelfia", "Filadelfia"),
	("Filandia", "Filandia"),
	("Firavitoba", "Firavitoba"),
	("Flandes", "Flandes"),
	("Florencia", "Florencia"),
	("Floresta", "Floresta"),
	("Florian", "Florian"),
	("Florida", "Florida"),
	("Floridablanca", "Floridablanca"),
	("Fomeque", "Fomeque"),
	("Fonseca", "Fonseca"),
	("Fortul", "Fortul"),
	("Fosca", "Fosca"),
	("Francisco Pizarro", "Francisco Pizarro"),
	("Fredonia", "Fredonia"),
	("Fresno", "Fresno"),
	("Frontino", "Frontino"),
	("Fuente de Oro", "Fuente de Oro"),
	("Fundacion", "Fundacion"),
	("Funes", "Funes"),
	("Funza", "Funza"),
	("Fúquene", "Fúquene"),
	("Fusagasuga", "Fusagasuga"),
	("Gachala", "Gachala"),
	("Gachancipa", "Gachancipa"),
	("Gachantiva", "Gachantiva"),
	("Gacheta", "Gacheta"),
	("Galan", "Galan"),
	("Galapa", "Galapa"),
	("Galeras (Nueva Granada)", "Galeras (Nueva Granada)"),
	("Gama", "Gama"),
	("Gamarra", "Gamarra"),
	("Gambita", "Gambita"),
	("Gameza", "Gameza"),
	("Garagoa", "Garagoa"),
	("Garzon", "Garzon"),
	("Genova", "Genova"),
	("Gigante", "Gigante"),
	("Ginebra", "Ginebra"),
	("Giraldo", "Giraldo"),
	("Girardot", "Girardot"),
	("Girardota", "Girardota"),
	("Giron", "Giron"),
	("Gomez Plata", "Gomez Plata"),
	("Gonzalez", "Gonzalez"),
	("Gramalote", "Gramalote"),
	("Granada", "Granada"),
	("Guaca", "Guaca"),
	("Guacamayas", "Guacamayas"),
	("Guacari", "Guacari"),
	("Guacheta", "Guacheta"),
	("Guachucal", "Guachucal"),
	("Guadalupe", "Guadalupe"),
	("Guaduas", "Guaduas"),
	("Guaitarilla", "Guaitarilla"),
	("Gualmatan", "Gualmatan"),
	("Guamal", "Guamal"),
	("Guamo", "Guamo"),
	("Guapi", "Guapi"),
	("Guapota", "Guapota"),
	("Guaranda", "Guaranda"),
	("Guarne", "Guarne"),
	("Guasca", "Guasca"),
	("Guatape", "Guatape"),
	("Guataqui", "Guataqui"),
	("Guatavita", "Guatavita"),
	("Guateque", "Guateque"),
	("Guatica", "Guatica"),
	("Guavata", "Guavata"),
	("Guayabal de Siquima", "Guayabal de Siquima"),
	("Guayabetal", "Guayabetal"),
	("Guayata", "Guayata"),
	("Guepsa", "Guepsa"),
	("Guican", "Guican"),
	("Gutierrez", "Gutierrez"),
	("Hacari", "Hacari"),
	("Hatillo de Loba", "Hatillo de Loba"),
	("Hato", "Hato"),
	("Hato Corozal", "Hato Corozal"),
	("Hatonuevo", "Hatonuevo"),
	("Heliconia", "Heliconia"),
	("Herran", "Herran"),
	("Herveo", "Herveo"),
	("Hispania", "Hispania"),
	("Hobo", "Hobo"),
	("Honda", "Honda"),
	("Ibague", "Ibague"),
	("Icononzo", "Icononzo"),
	("Iles", "Iles"),
	("Imúes", "Imúes"),
	("Inza", "Inza"),
	("Ipiales", "Ipiales"),
	("Iquira", "Iquira"),
	("Isnos", "Isnos"),
	("Itagüi", "Itagüi"),
	("Itsmina", "Itsmina"),
	("Ituango", "Ituango"),
	("Iza", "Iza"),
	("Jambalo", "Jambalo"),
	("Jamundi", "Jamundi"),
	("Jardin", "Jardin"),
	("Jenesano", "Jenesano"),
	("Jerico", "Jerico"),
	("Jerusalen", "Jerusalen"),
	("Jesús Maria", "Jesús Maria"),
	("Jordan", "Jordan"),
	("Juan de Acosta", "Juan de Acosta"),
	("Junin", "Junin"),
	("Jurado", "Jurado"),
	("La Apartada (Frontera)", "La Apartada (Frontera)"),
	("La Argentina", "La Argentina"),
	("La Belleza", "La Belleza"),
	("La Calera", "La Calera"),
	("La Capilla", "La Capilla"),
	("La Ceja", "La Ceja"),
	("La Celia", "La Celia"),
	("La Cruz", "La Cruz"),
	("La Cumbre", "La Cumbre"),
	("La Dorada", "La Dorada"),
	("La Esperanza", "La Esperanza"),
	("La Estrella", "La Estrella"),
	("La Florida", "La Florida"),
	("La Gloria", "La Gloria"),
	("La Jagua de Ibirico", "La Jagua de Ibirico"),
	("La Llanada", "La Llanada"),
	("La Macarena", "La Macarena"),
	("La Merced", "La Merced"),
	("La Mesa", "La Mesa"),
	("La Montañita", "La Montañita"),
	("La Palma", "La Palma"),
	("La Paz", "La Paz"),
	("La Paz (Robles)", "La Paz (Robles)"),
	("La Peña", "La Peña"),
	("La Pintada", "La Pintada"),
	("La Plata", "La Plata"),
	("La Playa", "La Playa"),
	("La Primavera", "La Primavera"),
	("La Salina", "La Salina"),
	("La Sierra", "La Sierra"),
	("La Tebaida", "La Tebaida"),
	("La Tola", "La Tola"),
	("La Ubita", "La Ubita"),
	("La Union", "La Union"),
	("La Uribe", "La Uribe"),
	("La Vega", "La Vega"),
	("La Victoria", "La Victoria"),
	("La Virginia", "La Virginia"),
	("Labateca", "Labateca"),
	("Labranzagrande", "Labranzagrande"),
	("Landazuri", "Landazuri"),
	("Lebrija", "Lebrija"),
	("Leiva", "Leiva"),
	("Lejanias", "Lejanias"),
	("Lenguazaque", "Lenguazaque"),
	("Lerida", "Lerida"),
	("Leticia", "Leticia"),
	("Libano", "Libano"),
	("Liborina", "Liborina"),
	("Linares", "Linares"),
	("Lloro", "Lloro"),
	("Lopez (Micay)", "Lopez (Micay)"),
	("Lorica", "Lorica"),
	("Los Andes (Sotomayor)", "Los Andes (Sotomayor)"),
	("Los Cordobas", "Los Cordobas"),
	("Los Palmitos", "Los Palmitos"),
	("Los Patios", "Los Patios"),
	("Los Santos", "Los Santos"),
	("Lourdes", "Lourdes"),
	("Luruaco", "Luruaco"),
	("Macanal", "Macanal"),
	("Macaravita", "Macaravita"),
	("Maceo", "Maceo"),
	("Macheta", "Macheta"),
	("Madrid", "Madrid"),
	("Magangue", "Magangue"),
	("Magüi (Payan)", "Magüi (Payan)"),
	("Mahates", "Mahates"),
	("Maicao", "Maicao"),
	("Majagual", "Majagual"),
	("Malaga", "Malaga"),
	("Malambo", "Malambo"),
	("Mallama (Piedrancha)", "Mallama (Piedrancha)"),
	("Manati", "Manati"),
	("Manaure", "Manaure"),
	("Manaure Balcon Cesar", "Manaure Balcon Cesar"),
	("Mani", "Mani"),
	("Manizales", "Manizales"),
	("Manta", "Manta"),
	("Manzanares", "Manzanares"),
	("Mapiripan", "Mapiripan"),
	("Margarita", "Margarita"),
	("Maria la Baja", "Maria la Baja"),
	("Marinilla", "Marinilla"),
	("Maripi", "Maripi"),
	("Mariquita", "Mariquita"),
	("Marmato", "Marmato"),
	("Marquetalia", "Marquetalia"),
	("Marsella", "Marsella"),
	("Marulanda", "Marulanda"),
	("Matanza", "Matanza"),
	("Medellin", "Medellin"),
	("Medina", "Medina"),
	("Melgar", "Melgar"),
	("Mercaderes", "Mercaderes"),
	("Mesetas", "Mesetas"),
	("Milan", "Milan"),
	("Miraflores", "Miraflores"),
	("Miranda", "Miranda"),
	("Mistrato", "Mistrato"),
	("Mitú", "Mitú"),
	("Mocoa", "Mocoa"),
	("Mogotes", "Mogotes"),
	("Molagavita", "Molagavita"),
	("Momil", "Momil"),
	("Mompos", "Mompos"),
	("Mongua", "Mongua"),
	("Mongui", "Mongui"),
	("Moniquira", "Moniquira"),
	("Monitos", "Monitos"),
	("Montebello", "Montebello"),
	("Montecristo", "Montecristo"),
	("Montelibano", "Montelibano"),
	("Montenegro", "Montenegro"),
	("Monteria", "Monteria"),
	("Monterrey", "Monterrey"),
	("Morales", "Morales"),
	("Morelia", "Morelia"),
	("Morroa", "Morroa"),
	("Mosquera", "Mosquera"),
	("Motavita", "Motavita"),
	("Murillo", "Murillo"),
	("Murindo", "Murindo"),
	("Mutata", "Mutata"),
	("Mutiscua", "Mutiscua"),
	("Muzo", "Muzo"),
	("Nariño", "Nariño"),
	("Nataga", "Nataga"),
	("Natagaima", "Natagaima"),
	("Nechi", "Nechi"),
	("Necocli", "Necocli"),
	("Neira", "Neira"),
	("Neiva", "Neiva"),
	("Nemocon", "Nemocon"),
	("Nilo", "Nilo"),
	("Nimaima", "Nimaima"),
	("Nobsa", "Nobsa"),
	("Nocaima", "Nocaima"),
	("Novita", "Novita"),
	("Nuevo Colon", "Nuevo Colon"),
	("Nunchia", "Nunchia"),
	("Nuqui", "Nuqui"),
	("Obando", "Obando"),
	("Ocamonte", "Ocamonte"),
	("Ocaña", "Ocaña"),
	("Oiba", "Oiba"),
	("Oicata", "Oicata"),
	("Olaya", "Olaya"),
	("Onzaga", "Onzaga"),
	("Oporapa", "Oporapa"),
	("Orito", "Orito"),
	("Orocue", "Orocue"),
	("Ortega", "Ortega"),
	("Ospina", "Ospina"),
	("Otanche", "Otanche"),
	("Ovejas", "Ovejas"),
	("Pachavita", "Pachavita"),
	("Pacho", "Pacho"),
	("Pacora", "Pacora"),
	("Padilla", "Padilla"),
	("Paez", "Paez"),
	("Paez (Belalcazar)", "Paez (Belalcazar)"),
	("Paicol", "Paicol"),
	("Pailitas", "Pailitas"),
	("Paime", "Paime"),
	("Paipa", "Paipa"),
	("Pajarito", "Pajarito"),
	("Palermo", "Palermo"),
	("Palestina", "Palestina"),
	("Palmar", "Palmar"),
	("Palmar de Varela", "Palmar de Varela"),
	("Palmas del Socorro", "Palmas del Socorro"),
	("Palmira", "Palmira"),
	("Palmito", "Palmito"),
	("Palocabildo", "Palocabildo"),
	("Pamplona", "Pamplona"),
	("Pamplonita", "Pamplonita"),
	("Pandi", "Pandi"),
	("Panqueba", "Panqueba"),
	("Paramo", "Paramo"),
	("Paratebueno", "Paratebueno"),
	("Pasca", "Pasca"),
	("Pasto", "Pasto"),
	("Patia (El Bordo)", "Patia (El Bordo)"),
	("Pauna", "Pauna"),
	("Paya", "Paya"),
	("Paz de Ariporo", "Paz de Ariporo"),
	("Paz de Rio", "Paz de Rio"),
	("Pedraza", "Pedraza"),
	("Pelaya", "Pelaya"),
	("Pensilvania", "Pensilvania"),
	("Peñol", "Peñol"),
	("Peque", "Peque"),
	("Pereira", "Pereira"),
	("Pesca", "Pesca"),
	("Piamonte", "Piamonte"),
	("Pie de Cuesta", "Pie de Cuesta"),
	("Piedras", "Piedras"),
	("Piendamo", "Piendamo"),
	("Pijao", "Pijao"),
	("Pijiño del Carmen", "Pijiño del Carmen"),
	("Pinchote", "Pinchote"),
	("Pinillos", "Pinillos"),
	("Piojo", "Piojo"),
	("Pisva", "Pisva"),
	("Pital", "Pital"),
	("Pitalito", "Pitalito"),
	("Pivijay", "Pivijay"),
	("Planadas", "Planadas"),
	("Planeta Rica", "Planeta Rica"),
	("Plato", "Plato"),
	("Policarpa", "Policarpa"),
	("Polonuevo", "Polonuevo"),
	("Ponedera", "Ponedera"),
	("Popayan", "Popayan"),
	("Pore", "Pore"),
	("Potosi", "Potosi"),
	("Pradera", "Pradera"),
	("Prado", "Prado"),
	("Providencia", "Providencia"),
	("Publoviejo", "Publoviejo"),
	("Pueblo Bello", "Pueblo Bello"),
	("Pueblo Nuevo", "Pueblo Nuevo"),
	("Pueblo Rico", "Pueblo Rico"),
	("Pueblorrico", "Pueblorrico"),
	("Puente Nacional", "Puente Nacional"),
	("Puerres", "Puerres"),
	("Puerto Asis", "Puerto Asis"),
	("Puerto Berrio", "Puerto Berrio"),
	("Puerto Boyaca", "Puerto Boyaca"),
	("Puerto Caicedo", "Puerto Caicedo"),
	("Puerto Carreño", "Puerto Carreño"),
	("Puerto Colombia", "Puerto Colombia"),
	("Puerto Concordia", "Puerto Concordia"),
	("Puerto Escondido", "Puerto Escondido"),
	("Puerto Gaitan", "Puerto Gaitan"),
	("Puerto Guzman", "Puerto Guzman"),
	("Puerto Inirida", "Puerto Inirida"),
	("Puerto Leguizamo", "Puerto Leguizamo"),
	("Puerto Libertador", "Puerto Libertador"),
	("Puerto Lleras", "Puerto Lleras"),
	("Puerto Lopez", "Puerto Lopez"),
	("Puerto Nare", "Puerto Nare"),
	("Puerto Nariño", "Puerto Nariño"),
	("Puerto Parra", "Puerto Parra"),
	("Puerto Rico", "Puerto Rico"),
	("Puerto Rondon", "Puerto Rondon"),
	("Puerto Salgar", "Puerto Salgar"),
	("Puerto Santander", "Puerto Santander"),
	("Puerto Tejada", "Puerto Tejada"),
	("Puerto Triunfo", "Puerto Triunfo"),
	("Puerto Wilches", "Puerto Wilches"),
	("Puli", "Puli"),
	("Pupiales", "Pupiales"),
	("Purace (Coconuco)", "Purace (Coconuco)"),
	("Purificacion", "Purificacion"),
	("Purisima", "Purisima"),
	("Quebradanegra", "Quebradanegra"),
	("Quetame", "Quetame"),
	("Quibdo", "Quibdo"),
	("Quimbaya", "Quimbaya"),
	("Quinchia", "Quinchia"),
	("Quipama", "Quipama"),
	("Quipile", "Quipile"),
	("Ricaurte", "Ricaurte"),
	("Rio de Oro", "Rio de Oro"),
	("Rio Viejo", "Rio Viejo"),
	("Rioblanco", "Rioblanco"),
	("Riofrio", "Riofrio"),
	("Riohacha", "Riohacha"),
	("Rionegro", "Rionegro"),
	("Riosucio", "Riosucio"),
	("Risaralda", "Risaralda"),
	("Rivera", "Rivera"),
	("Roberto Payan (San Jose)", "Roberto Payan (San Jose)"),
	("Roldanillo", "Roldanillo"),
	("Roncesvalles", "Roncesvalles"),
	("Rondon", "Rondon"),
	("Rosas", "Rosas"),
	("Rovira", "Rovira"),
	("Sabalarga", "Sabalarga"),
	("Sabana de Torres", "Sabana de Torres"),
	("Sabanagrande", "Sabanagrande"),
	("Sabanalarga", "Sabanalarga"),
	("Sabaneta", "Sabaneta"),
	("Saboya", "Saboya"),
	("Sacama", "Sacama"),
	("Sachica", "Sachica"),
	("Sahagún", "Sahagún"),
	("Saladoblanco", "Saladoblanco"),
	("Salamina", "Salamina"),
	("Salazar", "Salazar"),
	("Saldaña", "Saldaña"),
	("Salento", "Salento"),
	("Salgar", "Salgar"),
	("Samaca", "Samaca"),
	("Samana", "Samana"),
	("Samaniego", "Samaniego"),
	("Sampues", "Sampues"),
	("San Agustin", "San Agustin"),
	("San Alberto", "San Alberto"),
	("San Andres", "San Andres"),
	("San Andres Sotavento", "San Andres Sotavento"),
	("San Antero", "San Antero"),
	("San Antonio", "San Antonio"),
	("San Antonio de Tequendama", "San Antonio de Tequendama"),
	("San Benito", "San Benito"),
	("San Benito Abad", "San Benito Abad"),
	("San Bernardo", "San Bernardo"),
	("San Bernardo del Viento", "San Bernardo del Viento"),
	("San Calixto", "San Calixto"),
	("San Carlos", "San Carlos"),
	("San Carlos de Guaroa", "San Carlos de Guaroa"),
	("San Cayetano", "San Cayetano"),
	("San Cristobal", "San Cristobal"),
	("San Diego", "San Diego"),
	("San Eduardo", "San Eduardo"),
	("San Estanislao", "San Estanislao"),
	("San Fernando", "San Fernando"),
	("San Francisco", "San Francisco"),
	("San Gil", "San Gil"),
	("San Jacinto", "San Jacinto"),
	("San Jacinto del Cauca", "San Jacinto del Cauca"),
	("San Jeronimo", "San Jeronimo"),
	("San Joaquin", "San Joaquin"),
	("San Jose", "San Jose"),
	("San Jose de Miranda", "San Jose de Miranda"),
	("San Jose de Montaña", "San Jose de Montaña"),
	("San Jose de Pare", "San Jose de Pare"),
	("San Jose del Fragua", "San Jose del Fragua"),
	("San Jose del Guaviare", "San Jose del Guaviare"),
	("San Jose del Palmar", "San Jose del Palmar"),
	("San Juan de Arama", "San Juan de Arama"),
	("San Juan de Betulia", "San Juan de Betulia"),
	("San Juan de Rioseco", "San Juan de Rioseco"),
	("San Juan de Uraba", "San Juan de Uraba"),
	("San Juan del Cesar", "San Juan del Cesar"),
	("San Juan Nepomuceno", "San Juan Nepomuceno"),
	("San Juanito", "San Juanito"),
	("San Lorenzo", "San Lorenzo"),
	("San Luis", "San Luis"),
	("San Luis de Gaceno", "San Luis de Gaceno"),
	("San Luis de Palenque", "San Luis de Palenque"),
	("San Marcos", "San Marcos"),
	("San Martin", "San Martin"),
	("San Martin de Loba", "San Martin de Loba"),
	("San Mateo", "San Mateo"),
	("San Miguel", "San Miguel"),
	("San Miguel de Sema", "San Miguel de Sema"),
	("San Onofre", "San Onofre"),
	("San Pablo", "San Pablo"),
	("San Pablo de Borbur", "San Pablo de Borbur"),
	("San Pedro", "San Pedro"),
	("San Pedro de Cartago", "San Pedro de Cartago"),
	("San Pedro de Uraba", "San Pedro de Uraba"),
	("San Pelayo", "San Pelayo"),
	("San Rafael", "San Rafael"),
	("San Roque", "San Roque"),
	("San Sebastian", "San Sebastian"),
	("San Sebastian de Buuenavista", "San Sebastian de Buuenavista"),
	("San Vicente", "San Vicente"),
	("San Vicente de Chucuri", "San Vicente de Chucuri"),
	("San Vicente del Caguan", "San Vicente del Caguan"),
	("San Zenon", "San Zenon"),
	("Sandona", "Sandona"),
	("Santa Ana", "Santa Ana"),
	("Santa Barbara", "Santa Barbara"),
	("Santa Barbara (Iscuande)", "Santa Barbara (Iscuande)"),
	("Santa Catalina", "Santa Catalina"),
	("Santa Cruz (Guachavez)", "Santa Cruz (Guachavez)"),
	("Santa Helena del Opon", "Santa Helena del Opon"),
	("Santa Isabel", "Santa Isabel"),
	("Santa Lucia", "Santa Lucia"),
	("Santa Maria", "Santa Maria"),
	("Santa Marta", "Santa Marta"),
	("Santa Rosa", "Santa Rosa"),
	("Santa Rosa de Cabal", "Santa Rosa de Cabal"),
	("Santa Rosa de Osos", "Santa Rosa de Osos"),
	("Santa Rosa de Viterbo", "Santa Rosa de Viterbo"),
	("Santa Rosa del Sur", "Santa Rosa del Sur"),
	("Santa Rosalia", "Santa Rosalia"),
	("Santa Sofia", "Santa Sofia"),
	("Santafe de Bogota", "Santafe de Bogota"),
	("Santana", "Santana"),
	("Santander de Quilichao", "Santander de Quilichao"),
	("Santiago", "Santiago"),
	("Santo Domingo", "Santo Domingo"),
	("Santo Tomas", "Santo Tomas"),
	("Santuario", "Santuario"),
	("Sapuyes", "Sapuyes"),
	("Saravena", "Saravena"),
	("Sardinata", "Sardinata"),
	("Sasaima", "Sasaima"),
	("Sativanorte", "Sativanorte"),
	("Sativasur", "Sativasur"),
	("Segovia", "Segovia"),
	("Sesquile", "Sesquile"),
	("Sevilla", "Sevilla"),
	("Siachoque", "Siachoque"),
	("Sibate", "Sibate"),
	("Sibundoy", "Sibundoy"),
	("Silos", "Silos"),
	("Silvania", "Silvania"),
	("Silvia", "Silvia"),
	("Simacota", "Simacota"),
	("Simijaca", "Simijaca"),
	("Simiti", "Simiti"),
	("Since", "Since"),
	("Sincelejo", "Sincelejo"),
	("Sipi", "Sipi"),
	("Sitionuevo", "Sitionuevo"),
	("Soacha", "Soacha"),
	("Soata", "Soata"),
	("Socha", "Socha"),
	("Socorro", "Socorro"),
	("Socota", "Socota"),
	("Sogamoso", "Sogamoso"),
	("Solano", "Solano"),
	("Soledad", "Soledad"),
	("Solita", "Solita"),
	("Somondoco", "Somondoco"),
	("Sonson", "Sonson"),
	("Sopetran", "Sopetran"),
	("Soplaviento", "Soplaviento"),
	("Sopo", "Sopo"),
	("Sora", "Sora"),
	("Soraca", "Soraca"),
	("Sotaquira", "Sotaquira"),
	("Sotara (Paispamba)", "Sotara (Paispamba)"),
	("Suaita", "Suaita"),
	("Suan", "Suan"),
	("Suarez", "Suarez"),
	("Suaza", "Suaza"),
	("Subachoque", "Subachoque"),
	("Sucre", "Sucre"),
	("Suesca", "Suesca"),
	("Supata", "Supata"),
	("Supia", "Supia"),
	("Surata", "Surata"),
	("Susa", "Susa"),
	("Susacon", "Susacon"),
	("Sutamarchan", "Sutamarchan"),
	("Sutatausa", "Sutatausa"),
	("Sutatenza", "Sutatenza"),
	("Tabio", "Tabio"),
	("Tado", "Tado"),
	("Talaigua Nuevo", "Talaigua Nuevo"),
	("Tamalameque", "Tamalameque"),
	("Tamara", "Tamara"),
	("Tame", "Tame"),
	("Tamesis", "Tamesis"),
	("Taminango", "Taminango"),
	("Tangua", "Tangua"),
	("Taraza", "Taraza"),
	("Tarqui", "Tarqui"),
	("Tarso", "Tarso"),
	("Tasco", "Tasco"),
	("Tatama", "Tatama"),
	("Tauramena", "Tauramena"),
	("Tausa", "Tausa"),
	("Tello", "Tello"),
	("Tena", "Tena"),
	("Tenerife", "Tenerife"),
	("Tenjo", "Tenjo"),
	("Tenza", "Tenza"),
	("Teorama", "Teorama"),
	("Teruel", "Teruel"),
	("Tesalia", "Tesalia"),
	("Tibacuy", "Tibacuy"),
	("Tibana", "Tibana"),
	("Tibasosa", "Tibasosa"),
	("Tibirita", "Tibirita"),
	("Tibú", "Tibú"),
	("Tierralta", "Tierralta"),
	("Timana", "Timana"),
	("Timbio", "Timbio"),
	("Timbiqui", "Timbiqui"),
	("Tinjaca", "Tinjaca"),
	("Tipacoque", "Tipacoque"),
	("Tiquisio (Puerto Rico)", "Tiquisio (Puerto Rico)"),
	("Titiribi", "Titiribi"),
	("Toca", "Toca"),
	("Tocaima", "Tocaima"),
	("Tocancipa", "Tocancipa"),
	("Togui", "Togui"),
	("Toledo", "Toledo"),
	("Tolú", "Tolú"),
	("Toluviejo", "Toluviejo"),
	("Tona", "Tona"),
	("Topaga", "Topaga"),
	("Topaipi", "Topaipi"),
	("Toribio", "Toribio"),
	("Toro", "Toro"),
	("Tota", "Tota"),
	("Totoro", "Totoro"),
	("Trinidad", "Trinidad"),
	("Trujillo", "Trujillo"),
	("Tubara", "Tubara"),
	("Tulua", "Tulua"),
	("Tumaco", "Tumaco"),
	("Tunja", "Tunja"),
	("Tunungua", "Tunungua"),
	("Túquerres", "Túquerres"),
	("Turbaco", "Turbaco"),
	("Turbana", "Turbana"),
	("Turbo", "Turbo"),
	("Turmeque", "Turmeque"),
	("Tuta", "Tuta"),
	("Tutaza", "Tutaza"),
	("Ubala", "Ubala"),
	("Ubaque", "Ubaque"),
	("Ubate", "Ubate"),
	("Ulloa", "Ulloa"),
	("Úmbita", "Úmbita"),
	("Une", "Une"),
	("Unguia", "Unguia"),
	("Uramita", "Uramita"),
	("Uribia", "Uribia"),
	("Urrao", "Urrao"),
	("Urumita", "Urumita"),
	("Usiacuri", "Usiacuri"),
	("Útica", "Útica"),
	("Valdivia", "Valdivia"),
	("Valencia", "Valencia"),
	("Valle de San Jose", "Valle de San Jose"),
	("Valle de San Juan", "Valle de San Juan"),
	("Valledupar", "Valledupar"),
	("Valparaiso", "Valparaiso"),
	("Vegachi", "Vegachi"),
	("Velez", "Velez"),
	("Venadillo", "Venadillo"),
	("Venecia", "Venecia"),
	("Venecia (Ospina Perez)", "Venecia (Ospina Perez)"),
	("Ventaquemada", "Ventaquemada"),
	("Vergara", "Vergara"),
	("Versalles", "Versalles"),
	("Vetas", "Vetas"),
	("Viani", "Viani"),
	("Victoria", "Victoria"),
	("Vigia del Fuerte", "Vigia del Fuerte"),
	("Vijes", "Vijes"),
	("Villa de Leyva", "Villa de Leyva"),
	("Villa del Rosario", "Villa del Rosario"),
	("Villa Gamuez (La Hormiga)", "Villa Gamuez (La Hormiga)"),
	("Villa Garzon", "Villa Garzon"),
	("Villacaro", "Villacaro"),
	("Villagomez", "Villagomez"),
	("Villahermosa", "Villahermosa"),
	("Villamaria", "Villamaria"),
	("Villanueva", "Villanueva"),
	("Villapinzon", "Villapinzon"),
	("Villarrica", "Villarrica"),
	("Villavicencio", "Villavicencio"),
	("Villavieja", "Villavieja"),
	("Villeta", "Villeta"),
	("Viota", "Viota"),
	("Viracacha", "Viracacha"),
	("Vistahermosa", "Vistahermosa"),
	("Viterbo", "Viterbo"),
	("Yacopi", "Yacopi"),
	("Yacuanquer", "Yacuanquer"),
	("Yaguara", "Yaguara"),
	("Yali", "Yali"),
	("Yarumal", "Yarumal"),
	("Yolombo", "Yolombo"),
	("Yondo (Casabe)", "Yondo (Casabe)"),
	("Yopal", "Yopal"),
	("Yotoco", "Yotoco"),
	("Yumbo", "Yumbo"),
	("Zambrano", "Zambrano"),
	("Zapatoca", "Zapatoca"),
	("Zaragoza", "Zaragoza"),
	("Zarzal", "Zarzal"),
	("Zetaquira", "Zetaquira"),
	("Zipacon", "Zipacon"),
	('Zipaquira', 'Zipaquira')
)


class Usuario(User):
	TIPO_ID = (
		("", "Tipo de identificación"),
		('CEDULA', 'Cedula'),
		('TARJETADEIDENTIDAD', 'Tarjeta de Identidad'),
		('NIT', 'Nit'),
		('PASAPORTE', 'Pasaporte')
	)

	tipo_id = models.CharField(max_length=20, choices=TIPO_ID)
	identificacion = models.CharField(max_length=15, unique=True, validators=[validators.RegexValidator(re.compile('^[0-9]+$'), ('identificacion no valida'), 'invalid')])
	telefono_fijo = models.CharField(max_length=15, blank=True, validators=[validators.RegexValidator(re.compile('^[0-9]+$'), ('telefono no valido'), 'invalid')])
	telefono_celular = models.CharField(max_length=15, validators=[validators.RegexValidator(re.compile('^[0-9]+$'), ('telefono no valido'), 'invalid')])


class Empresa(models.Model):
	first_name = models.CharField(max_length=50)
	username = models.CharField(max_length=50)
	nit = models.CharField(max_length=50, validators=[validators.RegexValidator(re.compile('^[0-9]+$'), ('numero no valida'))])
	logo = models.ImageField(upload_to='logos_empresas/')
	web = models.URLField()
	direccion = models.CharField(max_length=50)
	ciudad = models.CharField(max_length=50, choices=CIUDAD)
	active = models.BooleanField(default=True)

	def __str__(self):
		return self.first_name

	class Meta:
		verbose_name = "Empresa"
		verbose_name_plural = "Empresas"


class Cliente (models.Model):
	TIPO_ID = (
		("", "Tipo de identificación"),
		('CEDULA', 'Cedula'),
		('TARJETA DE IDENTIDAD', 'Tarjeta de Identidad'),
		('NIT', 'Nit'),
		('PASAPORTE', 'Pasaporte')
	)

	first_name = models.CharField(('Nombre'), max_length=50)
	last_name = models.CharField(('Apellido'), max_length=50)
	tipo_id = models.CharField(max_length=20, choices=TIPO_ID)
	identificacion = models.CharField(max_length=15, unique=True, validators=[validators.RegexValidator(re.compile('^[0-9]+$'), ('identificacion no valida'), 'invalid')])
	telefono_fijo = models.CharField(max_length=15, blank=True, validators=[validators.RegexValidator(re.compile('^[0-9]+$'), ('telefono no valido'), 'invalid')])
	telefono_celular = models.CharField(max_length=15, blank=True, validators=[validators.RegexValidator(re.compile('^[0-9]+$'), ('telefono no valido'), 'invalid')])
	direccion = models.CharField(max_length=50)
	barrio = models.CharField(max_length=50, blank=True)
	zona = models.CharField(max_length=50, blank=True, null=True)
	ciudad = models.CharField(max_length=50, null=True, blank=True, choices=CIUDAD)

	def __str__(self):
		str = self.identificacion
		return str

	class Meta:
		verbose_name = "Cliente"
		verbose_name_plural = "Clientes"


class Empleado(Usuario):
	CARGOS = (
		('', 'Selccion un Cargo'),
		('ADMINISTRADOR', 'Administrador'),
		('SUPERVISOR', 'Supervisor'),
		('ALISTADOR', 'Alistador'),
		('MOTORIZADO', 'Motorizado'),
	)
	fecha_nacimiento = models.DateField()
	cargo = models.CharField(max_length=20, choices=CARGOS)
	empresa = models.ForeignKey(Empresa)
	direccion = models.CharField(max_length=50)
	ciudad = models.CharField(max_length=50, choices=CIUDAD)

	def __str__(self):
		return self.first_name + " " + self.last_name

	class Meta:
		verbose_name = "Empleado"
		verbose_name_plural = "Empleados"

	def save(self, *args, **kwargs):
		if not len(self.password):
			self.password = make_password(self.identificacion)
		#
		super(Empleado, self).save(*args, **kwargs)
    #end def
